export default {
  LOAD_POKEDEX: 'LOAD_POKEDEX',
  LOAD_POKEMON_DETAIL: 'LOAD_POKEMON_DETAIL',
  LOAD_POKEMON_SHOWN: 'LOAD_POKEMON_SHOWN',

  LOAD_MOVES: 'LOAD_MOVES',
  LOAD_LEARNSETS: 'LOAD_LEARNSETS',
  LOAD_ABILITIES: 'LOAD_ABILITIES',

  LOAD_POKEMON_ABILITIES: 'LOAD_POKEMON_ABILITIES',
  LOAD_POKEMON_MOVESET: 'LOAD_POKEMON_MOVESET',
  LOAD_POKEMON_LEARNSET: 'LOAD_POKEMON_LEARNSET',

  LOAD_POKEMON_FROM_TYPE: 'LOAD_POKEMON_FROM_TYPE',

  ABILITIES_LOADING: 'ABILITIES_LOADING',
  POKEDEX_LOADING: 'POKEDEX_LOADING',
  MOVES_LOADING: 'MOVES_LOADING',
  LEARNSETS_LOADING: 'LEARNSETS_LOADING',

  LOAD_TEAMS: 'LOAD_TEAMS',
  DELETE_ONE_TEAM: 'DELETE_ONE_TEAM',
  MODIFY_TEAM: 'MODIFY TEAM',
  LOAD_ONE_TEAM: 'LOAD_ONE_TEAM',
  MODIFY_POKEMON: 'MODIFY_POKEMON',

  CREATE_TEAM: 'CREATE_TEAM',
  ADD_POKEMON_TO_TEAM: 'ADD_POKEMON_TO_TEAM',

};
