export default {
  LOAD_POKELIST: 'LOAD_POKELIST',
  LOAD_POKEMON: 'LOAD_POKEMON',

  LOAD_MOVES: 'LOAD_MOVES',
  LOAD_LEARNSET: 'LOAD_LEARNSET',
  LOAD_ABILITIES: 'LOAD_ABILITIES',

  LOAD_POKEMON_ABILITIES: 'LOAD_POKEMON_ABILITIES',
  LOAD_POKEMON_MOVESET: 'LOAD_POKEMON_MOVESET',
  LOAD_POKEMON_LEARNSET: 'LOAD_POKEMON_LEARNSET',
};
