export default {
  LOAD_POKEDEX: 'LOAD_POKEDEX',
  LOAD_POKEMON_DETAIL: 'LOAD_POKEMON_DETAIL',
  LOAD_POKEMON_SHOWN: 'LOAD_POKEMON_SHOWN',

  LOAD_MOVES: 'LOAD_MOVES',
  LOAD_LEARNSETS: 'LOAD_LEARNSETS',
  LOAD_ABILITIES: 'LOAD_ABILITIES',

  LOAD_POKEMON_ABILITIES: 'LOAD_POKEMON_ABILITIES',
  LOAD_POKEMON_MOVESET: 'LOAD_POKEMON_MOVESET',
  LOAD_POKEMON_LEARNSET: 'LOAD_POKEMON_LEARNSET',

  LOAD_POKEMON_FROM_TYPE: 'LOAD_POKEMON_FROM_TYPE',

  TEAM_ERROR: 'TEAM_ERROR',
  LOAD_TEAMS: 'LOAD_TEAMS',
  DELETE_ONE_TEAM: 'DELETE_ONE_TEAM',
  MODIFY_TEAM: 'MODIFY TEAM',
  LOAD_ONE_TEAM: 'LOAD_ONE_TEAM',
  MODIFY_POKEMON: 'MODIFY_POKEMON',

  CREATE_TEAM: 'CREATE_TEAM',
  ADD_POKEMON_TO_TEAM: 'ADD_POKEMON_TO_TEAM',
  SUBMIT_TEAM: 'SUBMIT_TEAM',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  DELETE_USER: 'DELETE_USER',
  MODIFY_USER: 'MODIFY_USER',

  USER_ERROR: 'USER_ERROR',

};
