export default [
  {
    id: 6,
    pokemons: [{
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }],
  },
  {
    id: 1,
    pokemons: [{
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }],
  },
  {
    id: 5,
    pokemons: [{
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }, {
      name: 'Shedinja',
      'name-jap': 'キュウコン',
      sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
      ability: {
        name: 'Wonder Guard',
        description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
      },
      id: 1,
      kg: 3,
      m: 0.75,
      baseStats: {
        hp: 42,
        atk: 42,
        spa: 42,
        def: 43,
        spd: 48,
        spe: 50,
      },
      type: ['ghost', 'bug'],
    }],
  },
];
