export default [
  {
    id: 1,
    pokemons: [
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 60, atk: 62, def: 63, spa: 80, spd: 80, spe: 60,
        },
        abilities: ['Overgrow'],
        eggGroups: ['Monster', 'Grass'],
        _id: '604909308168be57082e3ec7',
        num: '2',
        name: 'Ivysaur',
        types: ['Grass', 'Poison'],
        heightm: 1,
        weightkg: 13,
        color: 'Green',
        prevo: 'Bulbasaur',
        evoLevel: 16,
        evos: ['Venusaur'],

        id: 1,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 80, atk: 82, def: 83, spa: 100, spd: 100, spe: 80,
        },
        abilities: ['Overgrow'],
        eggGroups: ['Monster', 'Grass'],
        _id: '604909308168be57082e3ec8',
        num: '3',
        name: 'Venusaur',
        types: ['Grass', 'Poison'],
        heightm: 2,
        weightkg: 100,
        color: 'Green',
        prevo: 'Ivysaur',
        evoLevel: 32,
        otherFormes: ['Venusaur-Mega'],
        formeOrder: ['Venusaur', 'Venusaur-Mega'],
        canGigantamax: 'G-Max Vine Lash',

        id: 2,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 39, atk: 52, def: 43, spa: 60, spd: 50, spe: 65,
        },
        abilities: ['Blaze'],
        eggGroups: ['Monster', 'Dragon'],
        _id: '604909308168be57082e3ec9',
        num: '4',
        name: 'Charmander',
        types: ['Fire'],
        heightm: 0.6,
        weightkg: 8.5,
        color: 'Red',
        evos: ['Charmeleon'],

        id: 3,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 58, atk: 64, def: 58, spa: 80, spd: 65, spe: 80,
        },
        abilities: ['Blaze'],
        eggGroups: ['Monster', 'Dragon'],
        _id: '604909308168be57082e3eca',
        num: '5',
        name: 'Charmeleon',
        types: ['Fire'],
        heightm: 1.1,
        weightkg: 19,
        color: 'Red',
        prevo: 'Charmander',
        evoLevel: 16,
        evos: ['Charizard'],

        id: 4,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 78, atk: 84, def: 78, spa: 109, spd: 85, spe: 100,
        },
        abilities: ['Blaze'],
        eggGroups: ['Monster', 'Dragon'],
        _id: '604909308168be57082e3ecb',
        num: '6',
        name: 'Charizard',
        types: ['Fire', 'Flying'],
        heightm: 1.7,
        weightkg: 90.5,
        color: 'Red',
        prevo: 'Charmeleon',
        evoLevel: 36,
        otherFormes: ['Charizard-Mega-X', 'Charizard-Mega-Y'],
        formeOrder: ['Charizard', 'Charizard-Mega-X', 'Charizard-Mega-Y'],
        canGigantamax: 'G-Max Wildfire',
        id: 5,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 44, atk: 48, def: 65, spa: 50, spd: 64, spe: 43,
        },
        abilities: ['Torrent'],
        eggGroups: ['Monster', 'Water 1'],
        _id: '604909308168be57082e3ecc',
        num: '7',
        name: 'Squirtle',
        types: ['Water'],
        heightm: 0.5,
        weightkg: 9,
        color: 'Blue',
        evos: ['Wartortle'],

        id: 6,
      },
    ],
  },
  {
    id: 8,
    pokemons: [
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 60, atk: 62, def: 63, spa: 80, spd: 80, spe: 60,
        },
        abilities: ['Overgrow'],
        eggGroups: ['Monster', 'Grass'],
        _id: '604909308168be57082e3ec7',
        num: '2',
        name: 'Ivysaur',
        types: ['Grass', 'Poison'],
        heightm: 1,
        weightkg: 13,
        color: 'Green',
        prevo: 'Bulbasaur',
        evoLevel: 16,
        evos: ['Venusaur'],

        id: 1,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 80, atk: 82, def: 83, spa: 100, spd: 100, spe: 80,
        },
        abilities: ['Overgrow'],
        eggGroups: ['Monster', 'Grass'],
        _id: '604909308168be57082e3ec8',
        num: '3',
        name: 'Venusaur',
        types: ['Grass', 'Poison'],
        heightm: 2,
        weightkg: 100,
        color: 'Green',
        prevo: 'Ivysaur',
        evoLevel: 32,
        otherFormes: ['Venusaur-Mega'],
        formeOrder: ['Venusaur', 'Venusaur-Mega'],
        canGigantamax: 'G-Max Vine Lash',

        id: 2,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 39, atk: 52, def: 43, spa: 60, spd: 50, spe: 65,
        },
        abilities: ['Blaze'],
        eggGroups: ['Monster', 'Dragon'],
        _id: '604909308168be57082e3ec9',
        num: '4',
        name: 'Charmander',
        types: ['Fire'],
        heightm: 0.6,
        weightkg: 8.5,
        color: 'Red',
        evos: ['Charmeleon'],

        id: 3,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 58, atk: 64, def: 58, spa: 80, spd: 65, spe: 80,
        },
        abilities: ['Blaze'],
        eggGroups: ['Monster', 'Dragon'],
        _id: '604909308168be57082e3eca',
        num: '5',
        name: 'Charmeleon',
        types: ['Fire'],
        heightm: 1.1,
        weightkg: 19,
        color: 'Red',
        prevo: 'Charmander',
        evoLevel: 16,
        evos: ['Charizard'],

        id: 4,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 78, atk: 84, def: 78, spa: 109, spd: 85, spe: 100,
        },
        abilities: ['Blaze'],
        eggGroups: ['Monster', 'Dragon'],
        _id: '604909308168be57082e3ecb',
        num: '6',
        name: 'Charizard',
        types: ['Fire', 'Flying'],
        heightm: 1.7,
        weightkg: 90.5,
        color: 'Red',
        prevo: 'Charmeleon',
        evoLevel: 36,
        otherFormes: ['Charizard-Mega-X', 'Charizard-Mega-Y'],
        formeOrder: ['Charizard', 'Charizard-Mega-X', 'Charizard-Mega-Y'],
        canGigantamax: 'G-Max Wildfire',
        id: 5,
      },
      {
        genderRatio: { M: 0.875, F: 0.125 },
        baseStats: {
          hp: 44, atk: 48, def: 65, spa: 50, spd: 64, spe: 43,
        },
        abilities: ['Torrent'],
        eggGroups: ['Monster', 'Water 1'],
        _id: '604909308168be57082e3ecc',
        num: '7',
        name: 'Squirtle',
        types: ['Water'],
        heightm: 0.5,
        weightkg: 9,
        color: 'Blue',
        evos: ['Wartortle'],

        id: 6,
      },
    ],
  },

];
