export default {
  name: 'Shedinja',
  'name-jap': 'キュウコン',
  sprite: 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png',
  ability: {
    name: 'Wonder Guard',
    description: 'This Pokemon can only be damaged by supereffective moves and indirect damage.',
  },
  id: 1,
  kg: 3,
  m: 0.75,
  stats: {
    hp: 42,
    atk: 42,
    'sp-atk': 42,
    def: 43,
    'sp-def': 48,
    speed: 50,
  },
  type: ['ghost', 'bug'],
  evo: ['https://img.pokemondb.net/sprites/sword-shield/icon/nincada.png', 'https://img.pokemondb.net/sprites/sword-shield/icon/ninjask.png', 'https://img.pokemondb.net/sprites/sword-shield/icon/shedinja.png'],
  moves: [
    {
      num: 446,
      accuracy: true,
      basePower: 0,
      category: 'Status',
      desc: "Sets up a hazard on the foe's side of the field, damaging each foe that switches in. Can be used only once before failing. Foes lose 1/32, 1/16, 1/8, 1/4, or 1/2 of their maximum HP, rounded down, based on their weakness to the Rock type; 0.25x, 0.5x, neutral, 2x, or 4x, respectively. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
      shortDesc: 'Hurts foes on switch-in. Factors Rock weakness.',
      id: 'stealthrock',
      isViable: true,
      name: 'Stealth Rock',
      pp: 20,
      priority: 0,
      flags: { reflectable: 1 },
      sideCondition: 'stealthrock',

      secondary: false,
      target: 'foeSide',
      type: 'Rock',
      zMoveBoost: { def: 1 },
      contestType: 'Cool',
    }, {
      num: 446,
      accuracy: true,
      basePower: 0,
      category: 'Status',
      desc: "Sets up a hazard on the foe's side of the field, damaging each foe that switches in. Can be used only once before failing. Foes lose 1/32, 1/16, 1/8, 1/4, or 1/2 of their maximum HP, rounded down, based on their weakness to the Rock type; 0.25x, 0.5x, neutral, 2x, or 4x, respectively. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
      shortDesc: 'Hurts foes on switch-in. Factors Rock weakness.',
      id: 'stealthrock',
      isViable: true,
      name: 'Stealth Rock',
      pp: 20,
      priority: 0,
      flags: { reflectable: 1 },
      sideCondition: 'stealthrock',

      secondary: false,
      target: 'foeSide',
      type: 'Rock',
      zMoveBoost: { def: 1 },
      contestType: 'Cool',
    }, {
      num: 446,
      accuracy: true,
      basePower: 0,
      category: 'Status',
      desc: "Sets up a hazard on the foe's side of the field, damaging each foe that switches in. Can be used only once before failing. Foes lose 1/32, 1/16, 1/8, 1/4, or 1/2 of their maximum HP, rounded down, based on their weakness to the Rock type; 0.25x, 0.5x, neutral, 2x, or 4x, respectively. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
      shortDesc: 'Hurts foes on switch-in. Factors Rock weakness.',
      id: 'stealthrock',
      isViable: true,
      name: 'Stealth Rock',
      pp: 20,
      priority: 0,
      flags: { reflectable: 1 },
      sideCondition: 'stealthrock',

      secondary: false,
      target: 'foeSide',
      type: 'Rock',
      zMoveBoost: { def: 1 },
      contestType: 'Cool',
    }, {
      num: 446,
      accuracy: true,
      basePower: 0,
      category: 'Status',
      desc: "Sets up a hazard on the foe's side of the field, damaging each foe that switches in. Can be used only once before failing. Foes lose 1/32, 1/16, 1/8, 1/4, or 1/2 of their maximum HP, rounded down, based on their weakness to the Rock type; 0.25x, 0.5x, neutral, 2x, or 4x, respectively. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
      shortDesc: 'Hurts foes on switch-in. Factors Rock weakness.',
      id: 'stealthrock',
      isViable: true,
      name: 'Stealth Rock',
      pp: 20,
      priority: 0,
      flags: { reflectable: 1 },
      sideCondition: 'stealthrock',
      secondary: false,
      target: 'foeSide',
      type: 'Rock',
      zMoveBoost: { def: 1 },
      contestType: 'Cool',
    }, {
      num: 446,
      accuracy: true,
      basePower: 0,
      category: 'Status',
      desc: "Sets up a hazard on the foe's side of the field, damaging each foe that switches in. Can be used only once before failing. Foes lose 1/32, 1/16, 1/8, 1/4, or 1/2 of their maximum HP, rounded down, based on their weakness to the Rock type; 0.25x, 0.5x, neutral, 2x, or 4x, respectively. Can be removed from the foe's side if any foe uses Rapid Spin or Defog, or is hit by Defog.",
      shortDesc: 'Hurts foes on switch-in. Factors Rock weakness.',
      id: 'stealthrock',
      isViable: true,
      name: 'Stealth Rock',
      pp: 20,
      priority: 0,
      flags: { reflectable: 1 },
      sideCondition: 'stealthrock',

      secondary: false,
      target: 'foeSide',
      type: 'Rock',
      zMoveBoost: { def: 1 },
      contestType: 'Cool',
    },
  ],
};
